[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "minecraft-py-actions"
version = "0.1.0"
description = "Proyecto de ejemplo"

[tool.setuptools]
packages = ["auxiliar", "libs", "mocks", "src", "tests"]
